---
title: "ClinicalTrialData"
author: "Walter"
date: "April 4, 2020"
output: html_document
---
Create random study data
```{r}
library(dplyr)
library(ggplot2)
library(tidyr)
library(lme4)
study=seq(1,3,1)
criteriaVar=rep("Weight",3)
min=c(100,110,120)
max=c(120,130,140)
studies=data.frame(study,criteriaVar,min,max)
studies[,"criteriaVar"]=as.character(studies[,"criteriaVar"])

```
Add age to the inclusion criteria

```{r}
study=seq(1,3,1)
criteriaVar=rep("Age",3)
min=c(20,25,30)
max=c(50,55,60)
studies=rbind(studies,data.frame(study,criteriaVar,min,max))
minDf=studies[,-4] %>% spread(criteriaVar,min) %>% rename(Age.min=Age,Weight.min=Weight) 
maxDf=studies[,-3] %>% spread(criteriaVar,max) %>% rename(Age.max=Age,Weight.max=Weight)
studies = merge(minDf,maxDf,by="study")
#checking version control
studies = studies[,1:3]
studies = studies %>% rename(Age=Age.min,Weight=Weight.min)
```

```{r}
# add subjects
study=seq(1,3,1)
Age=c(20,30,20)
Weight=c(130,160,150)
studies=rbind(studies,data.frame(study,Age,Weight))

```
Add group and scores
```{r}
studies=studies[studies$study %in% c(1,2),] 
studies =studies %>% arrange(desc(study))
studies$group= rep(c("Control","Experimental"),2)
studies =studies %>% arrange(desc(group))


```
Add more subjects and scores
```{r}
study=rep(c(2,1),2)
Age=c(40,30,45,50)
Weight=c(120,120,130,120)
group=rep(c("Experimental","Control"),2)
studies=rbind(studies,data.frame(study,Age,Weight,group))
studies$score= rnorm(8,20,2)
studies[studies["group"]=="Experimental",]["score"]=studies[studies["group"]=="Experimental",]["score"]+4
```




Using lm to estimate means controlling for same study, score/age, score/weight differing in study
```{r}


out=lmer(score~group+(1|study),data=studies)
ranef(out)
outCI= confint(out)
outCI=outCI[3:4,]
rbind(outCI, colSums(outCI))
outCI= data.frame(outCI)
coef(out)
outSum=summary(out)


```

```{r}

```